/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server/jquery.js']) {
  _$jscoverage['server/jquery.js'] = [];
  _$jscoverage['server/jquery.js'][1] = 0;
}
_$jscoverage['server/jquery.js'].source = ["define('jquery', [], function () { return function () {}; }); // noop on server"];
_$jscoverage['server/jquery.js'][1]++;
define("jquery", [], (function () {
  _$jscoverage['server/jquery.js'][1]++;
  return (function () {
});
}));
