/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server/jitc/template.js']) {
  _$jscoverage['server/jitc/template.js'] = [];
  _$jscoverage['server/jitc/template.js'][1] = 0;
  _$jscoverage['server/jitc/template.js'][3] = 0;
  _$jscoverage['server/jitc/template.js'][5] = 0;
  _$jscoverage['server/jitc/template.js'][8] = 0;
  _$jscoverage['server/jitc/template.js'][12] = 0;
  _$jscoverage['server/jitc/template.js'][15] = 0;
  _$jscoverage['server/jitc/template.js'][16] = 0;
  _$jscoverage['server/jitc/template.js'][17] = 0;
}
_$jscoverage['server/jitc/template.js'].source = ["define(['utils/template'], function (tmp) {","","    'use strict';","","    return {","","        compile: function (template, templateEngine) {","            return templateEngine.compile(template);","        },","","        amdify: function (template, templateEngineName) {","            var engineDef = tmp.getTemplateEngineDef(templateEngineName),","                moduleData = 'define([\\'' + templateEngineName + '\\'], function(' + engineDef.export + ') {';","","            moduleData += 'return Handlebars.template(' + engineDef.handler.precompile(template);","            moduleData += ');});';","            return moduleData;","        }","","    };","","});"];
_$jscoverage['server/jitc/template.js'][1]++;
define(["utils/template"], (function (tmp) {
  _$jscoverage['server/jitc/template.js'][3]++;
  "use strict";
  _$jscoverage['server/jitc/template.js'][5]++;
  return ({compile: (function (template, templateEngine) {
  _$jscoverage['server/jitc/template.js'][8]++;
  return templateEngine.compile(template);
}), amdify: (function (template, templateEngineName) {
  _$jscoverage['server/jitc/template.js'][12]++;
  var engineDef = tmp.getTemplateEngineDef(templateEngineName), moduleData = ("define(['" + templateEngineName + "'], function(" + engineDef["export"] + ") {");
  _$jscoverage['server/jitc/template.js'][15]++;
  moduleData += ("return Handlebars.template(" + engineDef.handler.precompile(template));
  _$jscoverage['server/jitc/template.js'][16]++;
  moduleData += ");});";
  _$jscoverage['server/jitc/template.js'][17]++;
  return moduleData;
})});
}));
