/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['common/resolver/model.js']) {
  _$jscoverage['common/resolver/model.js'] = [];
  _$jscoverage['common/resolver/model.js'][1] = 0;
  _$jscoverage['common/resolver/model.js'][3] = 0;
  _$jscoverage['common/resolver/model.js'][5] = 0;
  _$jscoverage['common/resolver/model.js'][7] = 0;
  _$jscoverage['common/resolver/model.js'][18] = 0;
  _$jscoverage['common/resolver/model.js'][19] = 0;
}
_$jscoverage['common/resolver/model.js'].source = ["define(['underscore'], function (_) {","","    'use strict';","","    var subRegEx = /\\{\\{\\s*([^|}]+?)\\s*(?:\\|([^}]*))?\\s*\\}\\}/g;","","    return {","","        methodMap: {","            'create': 'POST',","            'update': 'PUT',","            'patch': 'PATCH',","            'delete': 'DELETE',","            'read': 'GET'","        },","","        substitute: function (s, o) {","            return s.replace ? s.replace(subRegEx, function (match, key) {","                return _.isUndefined(o[key]) ? match : o[key];","            }) : s;","        }","","","    };","","});"];
_$jscoverage['common/resolver/model.js'][1]++;
define(["underscore"], (function (_) {
  _$jscoverage['common/resolver/model.js'][3]++;
  "use strict";
  _$jscoverage['common/resolver/model.js'][5]++;
  var subRegEx = /\{\{\s*([^|}]+?)\s*(?:\|([^}]*))?\s*\}\}/g;
  _$jscoverage['common/resolver/model.js'][7]++;
  return ({methodMap: {"create": "POST", "update": "PUT", "patch": "PATCH", "delete": "DELETE", "read": "GET"}, substitute: (function (s, o) {
  _$jscoverage['common/resolver/model.js'][18]++;
  return (s.replace? s.replace(subRegEx, (function (match, key) {
  _$jscoverage['common/resolver/model.js'][19]++;
  return (_.isUndefined(o[key])? match: o[key]);
})): s);
})});
}));
