/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['client/assetsProvider.js']) {
  _$jscoverage['client/assetsProvider.js'] = [];
  _$jscoverage['client/assetsProvider.js'][3] = 0;
  _$jscoverage['client/assetsProvider.js'][5] = 0;
  _$jscoverage['client/assetsProvider.js'][8] = 0;
  _$jscoverage['client/assetsProvider.js'][13] = 0;
  _$jscoverage['client/assetsProvider.js'][16] = 0;
  _$jscoverage['client/assetsProvider.js'][24] = 0;
}
_$jscoverage['client/assetsProvider.js'].source = ["/*global define:false, LAZO:false*/","","define(['jquery'], function ($) {","","    var AssetsProvider = LAZO.app.assets.Provider.extend({","","        list: function (options) {","            $.ajax({","                data: {","                    componentName: options.componentName","                },","                error: function (error) {","                    options.error(error);","                },","                success: function (result) {","                    options.success(result);","                },","                url: '/assets'","            });","        }","","    });","","    return AssetsProvider;","});"];
_$jscoverage['client/assetsProvider.js'][3]++;
define(["jquery"], (function ($) {
  _$jscoverage['client/assetsProvider.js'][5]++;
  var AssetsProvider = LAZO.app.assets.Provider.extend({list: (function (options) {
  _$jscoverage['client/assetsProvider.js'][8]++;
  $.ajax({data: {componentName: options.componentName}, error: (function (error) {
  _$jscoverage['client/assetsProvider.js'][13]++;
  options.error(error);
}), success: (function (result) {
  _$jscoverage['client/assetsProvider.js'][16]++;
  options.success(result);
}), url: "/assets"});
})});
  _$jscoverage['client/assetsProvider.js'][24]++;
  return AssetsProvider;
}));
