/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['client/loader.js']) {
  _$jscoverage['client/loader.js'] = [];
  _$jscoverage['client/loader.js'][1] = 0;
  _$jscoverage['client/loader.js'][3] = 0;
  _$jscoverage['client/loader.js'][4] = 0;
  _$jscoverage['client/loader.js'][5] = 0;
  _$jscoverage['client/loader.js'][6] = 0;
  _$jscoverage['client/loader.js'][7] = 0;
  _$jscoverage['client/loader.js'][11] = 0;
  _$jscoverage['client/loader.js'][14] = 0;
  _$jscoverage['client/loader.js'][17] = 0;
  _$jscoverage['client/loader.js'][19] = 0;
  _$jscoverage['client/loader.js'][20] = 0;
  _$jscoverage['client/loader.js'][25] = 0;
}
_$jscoverage['client/loader.js'].source = ["define(['module'], function (mod) {","","    function isServerOnly(name, paths) {","        var names = name.indexOf('/') ? name.split('/') : [name];","        for (var i = 0; i &lt; names.length; i++) {","            if (paths[names[i]] &amp;&amp; paths[names[i]].indexOf('/server/') !== -1) {","                return true;","            }","        }","","        return false;","    }","","    return {","        load: function (name, req, onload, config) {","            //req has the same API as require().","            if (name !== null &amp;&amp; name.indexOf('/server/') === -1 &amp;&amp; !isServerOnly(name, config.paths)) {","","                req([name], function (value) {","                    onload(value);","                });","","            } else {","                //Returning null for client side dependencies on server","                onload(null);","            }","        }","    };","","});"];
_$jscoverage['client/loader.js'][1]++;
define(["module"], (function (mod) {
  _$jscoverage['client/loader.js'][3]++;
  function isServerOnly(name, paths) {
    _$jscoverage['client/loader.js'][4]++;
    var names = (name.indexOf("/")? name.split("/"): [name]);
    _$jscoverage['client/loader.js'][5]++;
    for (var i = 0; (i < names.length); (i++)) {
      _$jscoverage['client/loader.js'][6]++;
      if ((paths[names[i]] && (paths[names[i]].indexOf("/server/") !== -1))) {
        _$jscoverage['client/loader.js'][7]++;
        return true;
      }
}
    _$jscoverage['client/loader.js'][11]++;
    return false;
}
  _$jscoverage['client/loader.js'][14]++;
  return ({load: (function (name, req, onload, config) {
  _$jscoverage['client/loader.js'][17]++;
  if (((name !== null) && (name.indexOf("/server/") === -1) && (! isServerOnly(name, config.paths)))) {
    _$jscoverage['client/loader.js'][19]++;
    req([name], (function (value) {
  _$jscoverage['client/loader.js'][20]++;
  onload(value);
}));
  }
  else {
    _$jscoverage['client/loader.js'][25]++;
    onload(null);
  }
})});
}));
