/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['client/prime.js']) {
  _$jscoverage['client/prime.js'] = [];
  _$jscoverage['client/prime.js'][1] = 0;
  _$jscoverage['client/prime.js'][3] = 0;
  _$jscoverage['client/prime.js'][4] = 0;
  _$jscoverage['client/prime.js'][7] = 0;
  _$jscoverage['client/prime.js'][8] = 0;
  _$jscoverage['client/prime.js'][11] = 0;
  _$jscoverage['client/prime.js'][12] = 0;
  _$jscoverage['client/prime.js'][16] = 0;
  _$jscoverage['client/prime.js'][17] = 0;
  _$jscoverage['client/prime.js'][18] = 0;
  _$jscoverage['client/prime.js'][22] = 0;
  _$jscoverage['client/prime.js'][23] = 0;
  _$jscoverage['client/prime.js'][29] = 0;
  _$jscoverage['client/prime.js'][30] = 0;
  _$jscoverage['client/prime.js'][34] = 0;
  _$jscoverage['client/prime.js'][35] = 0;
  _$jscoverage['client/prime.js'][36] = 0;
  _$jscoverage['client/prime.js'][37] = 0;
  _$jscoverage['client/prime.js'][41] = 0;
  _$jscoverage['client/prime.js'][42] = 0;
  _$jscoverage['client/prime.js'][46] = 0;
  _$jscoverage['client/prime.js'][47] = 0;
  _$jscoverage['client/prime.js'][48] = 0;
  _$jscoverage['client/prime.js'][50] = 0;
  _$jscoverage['client/prime.js'][51] = 0;
}
_$jscoverage['client/prime.js'].source = ["define(['jquery'], function ($) {","","    function primeCss(links, wait, callback) {","        var processed = 0,","            linkCount = links.length;","","        if (!LAZO.app.prefetchCss) {","            return callback ? callback(null) : void(0);","        }","","        for (var i = 0; i &lt; linkCount; i++) {","            $.ajax({","                url: links[i],","                dataType: 'text',","                success: function () {","                    processed++;","                    if (wait &amp;&amp; processed === linkCount &amp;&amp; callback) {","                        callback(null);","                    }","                },","                error: function (jqXHR, textStatus, errorThrown) {","                    if (callback) {","                        callback(errorThrown);","                    }","                }","            });","        }","","        if (!wait &amp;&amp; callback) {","            callback(null);","        }","    }","","    function primeJs(modules, wait, callback) {","        LAZO.require(modules, function () {","            if (wait &amp;&amp; callback) { // combo handled","                callback();","            }","        });","","        if (!wait &amp;&amp; callback) { // not combo handled; prefetch and prime the cache","            callback(null);","        }","    }","","    return function (resources, resourcesType, wait, callback) {","        if (resourcesType === 'css') {","            primeCss(resources, wait, callback);","        }","        if (resourcesType === 'js') {","            primeJs(resources, wait, callback);","        }","    };","","});"];
_$jscoverage['client/prime.js'][1]++;
define(["jquery"], (function ($) {
  _$jscoverage['client/prime.js'][3]++;
  function primeCss(links, wait, callback) {
    _$jscoverage['client/prime.js'][4]++;
    var processed = 0, linkCount = links.length;
    _$jscoverage['client/prime.js'][7]++;
    if ((! LAZO.app.prefetchCss)) {
      _$jscoverage['client/prime.js'][8]++;
      return (callback? callback(null): (void 0));
    }
    _$jscoverage['client/prime.js'][11]++;
    for (var i = 0; (i < linkCount); (i++)) {
      _$jscoverage['client/prime.js'][12]++;
      $.ajax({url: links[i], dataType: "text", success: (function () {
  _$jscoverage['client/prime.js'][16]++;
  (processed++);
  _$jscoverage['client/prime.js'][17]++;
  if ((wait && (processed === linkCount) && callback)) {
    _$jscoverage['client/prime.js'][18]++;
    callback(null);
  }
}), error: (function (jqXHR, textStatus, errorThrown) {
  _$jscoverage['client/prime.js'][22]++;
  if (callback) {
    _$jscoverage['client/prime.js'][23]++;
    callback(errorThrown);
  }
})});
}
    _$jscoverage['client/prime.js'][29]++;
    if (((! wait) && callback)) {
      _$jscoverage['client/prime.js'][30]++;
      callback(null);
    }
}
  _$jscoverage['client/prime.js'][34]++;
  function primeJs(modules, wait, callback) {
    _$jscoverage['client/prime.js'][35]++;
    LAZO.require(modules, (function () {
  _$jscoverage['client/prime.js'][36]++;
  if ((wait && callback)) {
    _$jscoverage['client/prime.js'][37]++;
    callback();
  }
}));
    _$jscoverage['client/prime.js'][41]++;
    if (((! wait) && callback)) {
      _$jscoverage['client/prime.js'][42]++;
      callback(null);
    }
}
  _$jscoverage['client/prime.js'][46]++;
  return (function (resources, resourcesType, wait, callback) {
  _$jscoverage['client/prime.js'][47]++;
  if ((resourcesType === "css")) {
    _$jscoverage['client/prime.js'][48]++;
    primeCss(resources, wait, callback);
  }
  _$jscoverage['client/prime.js'][50]++;
  if ((resourcesType === "js")) {
    _$jscoverage['client/prime.js'][51]++;
    primeJs(resources, wait, callback);
  }
});
}));
