/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['common/utils/modelLoader.js']) {
  _$jscoverage['common/utils/modelLoader.js'] = [];
  _$jscoverage['common/utils/modelLoader.js'][1] = 0;
  _$jscoverage['common/utils/modelLoader.js'][2] = 0;
  _$jscoverage['common/utils/modelLoader.js'][4] = 0;
  _$jscoverage['common/utils/modelLoader.js'][5] = 0;
  _$jscoverage['common/utils/modelLoader.js'][8] = 0;
  _$jscoverage['common/utils/modelLoader.js'][9] = 0;
  _$jscoverage['common/utils/modelLoader.js'][13] = 0;
  _$jscoverage['common/utils/modelLoader.js'][18] = 0;
}
_$jscoverage['common/utils/modelLoader.js'].source = ["define(['lazoModel', 'lazoCollection'], function (LazoModel, LazoCollection) {","    'use strict';","","    var modelLoader = function (name, type, cb) {","        LAZO.require(['models/' + name + '/' + type],","            function (model) {","                // https://github.com/jrburke/requirejs/issues/922","                if (typeof model === 'function') {","                    cb(model);","                }","            },","            function (err) {","                cb(type === 'model' ? LazoModel : LazoCollection, true);","            }","        );","    };","","    return modelLoader;","});"];
_$jscoverage['common/utils/modelLoader.js'][1]++;
define(["lazoModel", "lazoCollection"], (function (LazoModel, LazoCollection) {
  _$jscoverage['common/utils/modelLoader.js'][2]++;
  "use strict";
  _$jscoverage['common/utils/modelLoader.js'][4]++;
  var modelLoader = (function (name, type, cb) {
  _$jscoverage['common/utils/modelLoader.js'][5]++;
  LAZO.require([("models/" + name + "/" + type)], (function (model) {
  _$jscoverage['common/utils/modelLoader.js'][8]++;
  if (((typeof model) === "function")) {
    _$jscoverage['common/utils/modelLoader.js'][9]++;
    cb(model);
  }
}), (function (err) {
  _$jscoverage['common/utils/modelLoader.js'][13]++;
  cb(((type === "model")? LazoModel: LazoCollection), true);
}));
});
  _$jscoverage['common/utils/modelLoader.js'][18]++;
  return modelLoader;
}));
